config/routes.rb
Rails.application.routes.draw do

  root to: 'customers#index'
  resources :customers
  
end

app/models/customer.rb
class Customer < ActiveRecord::Base

	validates :first_name, presence: true, length: { minimum: 2 }
	 validates :last_name, presence:true, length: {minimum: 2}
	 
	 # to be called in _customer.html.erb partial
	 # example: Jalan Binjai, 12345, Kuala Lumpur
	 def address
	 	if street.present? && zip.present? && city.present?
	 		"#{street}, #{zip}, #{city}"
	 	end
	 end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  
  def index
    @customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(customer_params)

    respond_to do |format|
      if @customer.save
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @customer.errors.full_messages, 
                            status: :unprocessable_entity }
      end
      
    end
  end

  def edit
  end

  def update
     respond_to do |format|
      if @customer.update(customer_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @customer.errors.full_messages,
                                   status: :unprocessable_entity }
      end
     
    end
  end


  def destroy

    @customer.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

private
  
  def set_customer
  	@customer = Customer.find(params[:id])
  end
  
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, 
                            :phone, :email, :street, :zip, :city)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<tr id="customer_<%= customer.id %>">
  <td><%= customer.first_name %></td>
  <td><%= customer.last_name %></td>
  <td><%= customer.email %></td>
  <td><%= customer.phone %></td>
  <td><%= customer.address %></td>
  <td>
    <%= link_to 'Edit', edit_customer_path(customer), remote: true, :class => 'btn btn-sm btn-info' %>
    <%= link_to 'Delete', customer, remote: true, :method => :delete, data: {confirm: "Delete Customer: #{customer.first_name} #{customer.last_name}"}, :class => 'btn btn-sm btn-danger' %>
  </td>
</tr>

app/views/customers/_dialog.html.erb
<div class="modal fade"
           id="dialog" tabindex="-1" role="dialog" 
           aria-labelledby="myModalLabel"
           aria-hidden="true" 
           data-backdrop="static" 
           data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" 
                data-dismiss="modal" 
                aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>
     
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/customers/_form.html.erb
<%= form_for(@customer, remote: true, :html => { :role => "form" }) do |f| %>
<div id="error_explanation" class="bg-danger text-danger">
</div>

<div class="row">
 <div class="col-sm-6">
  <div class="form-group">
    <%= f.label :first_name, :class => "control-label" %>
    <%= f.text_field :first_name, :class => "form-control first_input"  %>
  </div>
  <div class="form-group">
    <%= f.label :last_name, :class => "control-label" %>
    <%= f.text_field :last_name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => "control-label" %>
    <%= f.text_field :phone, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => "control-label" %>
    <%= f.text_field :email, :class => "form-control" %>
  </div>
</div>

<div class="col-sm-6">
  <div class="form-group">
    <%= f.label :street, :class => "control-label" %>
    <%= f.text_field :street, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :zip, :class => "control-label" %>
    <%= f.text_field :zip, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => "control-label" %>
    <%= f.text_field :city, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit  @customer.new_record? ? "Create Customer" : "Update Customer", :class => "btn btn-primary" %>
  </div>
</div>
</div>
<% end %>

app/views/customers/create.js.erb
$('#dialog').modal('toggle');
$('#customers').append('<%= j render (@customer) %>')
console.log("<%= @customer.first_name %> <%= @customer.last_name %> created");

app/views/customers/destroy.js.erb
$('#customer_<%= @customer.id %>').fadeOut();
console.log("Customer deleted");

app/views/customers/edit.js.erb
// Add the dialog title
$('#dialog h3').html("<i class=' glyphicon glyphicon-pencil'></i> Edit Customer");

// Render the edit form
$('.modal-body').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#dialog').modal("show");

// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })

app/views/customers/index.html.erb
<div class="container">

  <h2>Customers</h2>
  <div class="well">
    <%= link_to "New Customer", new_customer_path, remote: true, class: "btn btn-primary" %>
  </div>
  <div class="new-customer"></div>

  <table id class="table table-bordered table-striped">
    <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody id="customers">
    <%= render @customers %>
    </tbody>
  </table>

  <%= render 'dialog' %>

</div>

app/views/customers/new.js.erb
// Add the dialog title
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> Add New Customer");

// Render the new form
$('.modal-body').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#dialog').modal("show");

// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })

app/views/customers/update.js.erb
$('#dialog').modal('toggle');
$('#customer_<%= @customer.id %>').replaceWith('<%= j render (@customer) %>')
console.log("<%= @customer.first_name %> <%= @customer.last_name %> updated");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxBootstrapModals</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>